name: acta
description: A simple todo Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.15.1 <3.0.0'

dependencies:
    cupertino_icons: ^1.0.2
    firebase_auth: ^3.3.5
    firebase_core: ^1.11.0
    flutter:
        sdk: flutter
    flutter_colorpicker: ^1.0.3
    flutter_platform_widgets: ^1.12.1
    google_sign_in: ^5.2.3
    http: ^0.13.4
    intl: ^0.17.0
    platform_date_picker: ^0.2.0-nullsafety.0+1
    provider: ^6.0.2
    roundcheckbox: ^2.0.4+1

dev_dependencies:
    flutter_launcher_icons: ^0.9.2
    flutter_lints: ^1.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/

flutter_icons:
    remove_alpha_ios: true
    android: 'launcher_icon'
    ios: true
    image_path: 'assets/icon.png'
