// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdIfXOlOaisSLxjA-Id7LW27oFiAOTFs',
    appId: '1:160945447343:android:cfdee4cb184ef694998f5a',
    messagingSenderId: '160945447343',
    projectId: 'to-do-back',
    databaseURL: 'https://to-do-back-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-back.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk8hlPLaWEBkddd6i_tdMt_rDZuMr2qfM',
    appId: '1:160945447343:ios:8cb00640b802f1ca998f5a',
    messagingSenderId: '160945447343',
    projectId: 'to-do-back',
    databaseURL: 'https://to-do-back-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-back.appspot.com',
    androidClientId: '160945447343-ol4n08u0oat5nlsb79l48od0b15jl3ka.apps.googleusercontent.com',
    iosClientId: '160945447343-ja5p5s00ph8ucvdl3j8k29d2j0em467g.apps.googleusercontent.com',
    iosBundleId: 'com.example.acta',
  );
}
