// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoKrh8JODkWddPRux6lgw8S1pPh65cQmI',
    appId: '1:160945447343:android:412cdeb37621904c998f5a',
    messagingSenderId: '160945447343',
    projectId: 'to-do-back',
    databaseURL: 'https://to-do-back-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-back.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8N37vwyu8bRjQiyfL5dWirnWgVux5IQU',
    appId: '1:160945447343:ios:e419daf7868eb065998f5a',
    messagingSenderId: '160945447343',
    projectId: 'to-do-back',
    databaseURL: 'https://to-do-back-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-back.appspot.com',
    androidClientId: '160945447343-f0acj213848fc95ifhqphpnqrtjqtlq9.apps.googleusercontent.com',
    iosClientId: '160945447343-ccbh78avtjvifiuh84qrqu5qpv25o7h7.apps.googleusercontent.com',
    iosBundleId: 'com.acta.app',
  );
}
