name: Builds Flutter apk
uses: subosito/flutter-action@v2.2.0
on:
    push:
        tags:
            - '*'
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: 'zulu'
                  java-version: '11'
            - uses: subosito/flutter-action@v2
              with:
                  flutter-version: '2.8.1'
            - run: flutter pub get
            - run: flutter build apk --split-per-abi
            - name: get version
              id: version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - uses: ncipollo/release-action@v1
              with:
                  tag: ${{steps.version.outputs.prop}}
                  artifacts: 'build/app/outputs/apk/release/app-armeabi-v7a-release.apk'
                  body: ${{ github.event.commits[0].message }}
                  token: ${{ secrets.RELEASES_TOKEN }}
