name: Builds Flutter apk
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: subosito/flutter-action@v2.2.0
            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                  distribution: 'zulu'
                  java-version: '11'
            - name: Flutter setup
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: '2.x'
                  channel: 'stable'
            - name: Get flutter dependencies
              run: flutter pub get
              working-directory: acta
            - name: Decrypt Android keys
              run: sh ./.github/scripts/decrypt_android_keys.sh
              env:
                  ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
            - name: Build flutter apk
              run: flutter build apk --split-per-abi
              working-directory: acta
            - name: get version
              id: version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - uses: ncipollo/release-action@v1
              with:
                  tag: ${{steps.version.outputs.prop}}
                  artifacts: 'acta/build/app/outputs/apk/release/app-armeabi-v7a-release.apk'
                  body: ${{ github.event.commits[0].message }}
                  token: ${{ secrets.GITHUB_TOKEN }}
